Kitware/paraviewweb

src/IO/Girder/HpcCloudEndpoints/api.md
this commit is really to force a build and release through travis
=> fix(IO): documentation endpoint

documentation/www/source/docs/guides/os_mesa.md
=> doc(OSMesa): Update os_mesa.md

src/React/Widgets/ColorMapEditorWidget/api.md, src/React/Widgets/PieceWiseFunctionEditorWidget/api.md
=> Colormap editor docs

src/React/Widgets/PresetListWidget/api.md
=> docs(PresetListWidget): Add API for react properties

tools/ansible/roles/paraview/tasks/main.yml
Resolve Ansible 2.1 issue with becoming an unprivileged user.
=> fix(Ansible): Run directory creation as root

src/InfoViz/Core/D3MultiClick/index.js, src/InfoViz/Native/FieldSelector/index.js, src/InfoViz/Native/HistogramSelector/example/index.js, src/InfoViz/Native/HistogramSelector/example/state.json, src/InfoViz/Native/HistogramSelector/index.js, src/InfoViz/Native/index.js, style/InfoVizNative/FieldSelector.mcss, style/InfoVizNative/HistogramSelector.mcss
Functional histogram grid with an example using FeatureSelector to show the selection provider hook-up works. Brushing is present just to show it can be done, without any scoring GUI available yet. 
I'll squash commits after satisfying comments. 
@scottwittenburg @vibraphone comments? Merge now or keep going?
=> Histogram selector native component

src/React/CollapsibleControls/LightControl/index.js, src/React/CollapsibleControls/VolumeControl/index.js
=> fix(CollapsibleWidget): Add missing activeSubTitle property 

src/InfoViz/Native/HistogramSelector/example/index.js, src/InfoViz/Native/HistogramSelector/index.js, style/InfoVizNative/HistogramSelector.mcss
@scottwittenburg @vibraphone 
This scoring interface includes dividers and regions, but no pop-up windows for setting things yet. The score is cycled when you click on a region. Let me know what you think of the interaction...
@jourdain Any code style changes needed?
=> Histogram selector scoring GUI

README.md, package.json
Try to allow Windows to be used as a development platform
=> fix(Windows): Try to fix some Windows related issue

package.json, src/IO/Core/CSVReader/Processing.js, src/IO/Core/CSVReader/index.js, src/React/CollapsibleControls/CollapsibleControlFactory/index.js, src/React/CollapsibleControls/PlotlyChartControl/Histogram.js, src/React/CollapsibleControls/PlotlyChartControl/Histogram2D.js, src/React/CollapsibleControls/PlotlyChartControl/PieChart.js, src/React/CollapsibleControls/PlotlyChartControl/Scatter3D.js, src/React/CollapsibleControls/PlotlyChartControl/index.js, src/React/Renderers/PlotlyRenderer/index.js, src/React/Renderers/index.js, src/React/Viewers/AbstractViewerMenu/index.js, src/React/Viewers/ChartViewer/index.js, src/React/Viewers/index.js, src/Rendering/Chart/PlotlyChartBuilder/Histogram.js, src/Rendering/Chart/PlotlyChartBuilder/Histogram2D.js, src/Rendering/Chart/PlotlyChartBuilder/PieChart.js, src/Rendering/Chart/PlotlyChartBuilder/Scatter3D.js, src/Rendering/Chart/PlotlyChartBuilder/chartTypes.json, src/Rendering/Chart/PlotlyChartBuilder/index.js, src/Rendering/Chart/index.js, src/Rendering/index.js, style/ReactCollapsibleControls/PlotlyChartControl.mcss, style/ReactRenderers/PlotlyRenderer.mcss, style/ReactViewers/AbstractViewerMenu.mcss, style/ReactWidgets/PlotlySelectionWidgets.mcss
Adds a chart viewer with the ability to select several different
types of Plotly JS charts.
=> feat(ChartViewer): Add a basic chart viewer capability

src/InfoViz/Native/FieldSelector/index.js, src/InfoViz/Native/HistogramSelector/Score.js, src/InfoViz/Native/HistogramSelector/example/index.js, src/InfoViz/Native/HistogramSelector/index.js, style/InfoVizNative/FieldSelector.mcss, style/InfoVizNative/HistogramSelector.mcss
Closes #159 
Adds styling improvements requested by Patrick, and pop-up to edit divider value and uncertainty with exact numbers. 
@jourdain @scottwittenburg @vibraphone want to take a look?
=> Histogram scoring divider editing, with uncertainty

src/Common/Misc/SelectionBuilder/index.js, src/Common/Misc/SelectionBuilder/tests/test-selection-builder.js, src/Common/Misc/index.js
Add SelectionBuilder to improve selection handling across widgets
=> fix(SelectionBuilder): Add SelectionBuilder

src/InfoViz/Native/HistogramSelector/Score.js
While dragging and when committing to values in the divider popup, make the
uncertainty of the edited divider not overlap with neighbors. When the divider's
value is changed or it's dragged, if it ends up inside another divider's
uncertain region, shrink the other divider's uncertainty.
Also represent uncertainty internally as [0,1] instead of [0,100%]
to make communication with the server easier.
=> fix(HistogramSelector): Scoring - uncertainty regions shouldn't overlap

src/React/Containers/OverlayWindow/index.js, style/ReactContainers/OverlayWindow.mcss
Also grays out content window while drag or resize is being performed, and makes sure there are decent defaults for x, y, width, and height.
=> fix(OverlayWindow): Fix mouse events on content

src/Common/Misc/AnnotationBuilder/index.js, src/InfoViz/Core/ScoresProvider/index.js, src/InfoViz/Native/HistogramSelector/Score.js, src/InfoViz/Native/HistogramSelector/example/index.js, src/InfoViz/Native/HistogramSelector/index.js
Update to new selection and annotation format for communicating
with the provider. Provider still just communicates an object,
server is responsible for interpreting it.
=> Fix(HistogramSelector): Use SelectionBuilder to make partitions.

src/Component/Native/Workbench/index.js, src/InfoViz/Native/ParallelCoordinates/AxesManager.js, src/InfoViz/Native/ParallelCoordinates/index.js, src/React/Widgets/AnnotationEditorWidget/ManyScore/index.js, src/React/Widgets/AnnotationEditorWidget/ScoreSelector.js, src/React/Widgets/AnnotationEditorWidget/example/index.js, src/React/Widgets/AnnotationEditorWidget/index.js, style/ReactWidgets/AnnotationEditorWidget.mcss
=> More annotation work

src/Common/Misc/NumberFormatter/index.js, src/React/Widgets/SelectionEditorWidget/partition/DividerRender.js, src/React/Widgets/SelectionEditorWidget/range/FiveClauseRender.js, src/React/Widgets/SelectionEditorWidget/rule/FiveClauseRender.js
Add validation for negative and exponential numbers. Fix
bug in NumberFormatter for negative values.
=> fix(SelectionEditorWidget): Allow negatives and exponents

src/InfoViz/Native/MutualInformationDiagram/index.js
This commit adds some render state (displayed pmi chords, highlighted pmi chords) so that extra
render calls do not seem to reset the diagram.  Also fixes broken mouse move events so that outer
histogram bins are properly hovered when mouse is outside the circle.  Also unifies the render()
calls, as sometimes render() was called with a width and height, other times with the (unnecessary)
mutual informationdata.  Now render takes no arguments, similar to other components.
=> fix(MutualInfoDiagram): Fix several bugs

documentation/content/docs/guides/apache_front_end.md, documentation/content/docs/guides/python_launcher.md
=> docs(python): updated apache conf and python launcher line

documentation/config.js, src/Component/Native/Workbench/index.js, src/InfoViz/Core/FieldProvider/index.js, src/InfoViz/Native/FieldSelector/index.js, src/InfoViz/Native/HistogramSelector/index.js, src/InfoViz/Native/ParallelCoordinates/example/state.json, src/InfoViz/Native/ParallelCoordinates/index.js, style/InfoVizNative/HistogramSelector.mcss, webpack.config.js
@scottwittenburg @vibraphone A few of the comments from the meeting.
=> Native feel tweaks

src/InfoViz/Core/ScoresProvider/index.js, src/InfoViz/Native/MutualInformationDiagram/index.js, style/InfoVizNative/InformationDiagram.mcss
@jourdain @scottwittenburg Fix for HistogramSelector web example.
Plus several fixes for MI.
=> Mutual info mouse tweaks

src/InfoViz/Core/SelectionProvider/dataHelper.js, src/InfoViz/Core/SelectionProvider/histogram1d.js, src/InfoViz/Core/SelectionProvider/index.js, src/InfoViz/Native/HistogramSelector/index.js, src/InfoViz/Native/HistogramSelector/score.js
Adds a new histogram1D handler to SelectionProvider,
used by DataUpdateProvider to push 1D histograms to
the HistogramSelector.
@scottwittenburg
=> fix(HistogramProvider): base on DataUpdateProvider

src/InfoViz/Native/HistogramSelector/index.js, src/InfoViz/Native/HistogramSelector/score.js
Handle partial updates of the histogram data, and rescale partition
dividers if the histogram range changes. Put the hist data in
the already existing field data structure.
Handle min === max for histogram ranges, to avoid getting NaN
for uncertainties.
=> fix(HistogramSelector) hist partial updates, zero range hist.

src/InfoViz/Native/HistogramSelector/index.js, src/InfoViz/Native/HistogramSelector/score.js, src/React/Widgets/AnnotationStoreEditorWidget/index.js, style/InfoVizNative/HistogramSelector.mcss
=> Hist1d storage

src/InfoViz/Core/MutualInformationProvider/index.js, src/InfoViz/Core/MutualInformationProvider/pmi.js, src/InfoViz/Native/HistogramSelector/score.js, src/InfoViz/Native/MutualInformationDiagram/example/index.md, src/InfoViz/Native/MutualInformationDiagram/example/state.json, src/InfoViz/Native/MutualInformationDiagram/index.js, style/InfoVizNative/InformationDiagram.mcss
Fixing some IE errors and rendering problems, and a funny MI provider problem which skipped generating data for the first field.
I figured out how to measure textPath length in IE/Edge, with a hack. 
@jourdain @scottwittenburg take a look?
=> MutualInformation and HistogramSelector fixes

src/InfoViz/Native/MutualInformationDiagram/body.html, src/InfoViz/Native/MutualInformationDiagram/index.js, style/InfoVizNative/InformationDiagram.mcss
@vibraphone @jourdain 
If you have time, I'd appreciate an independent test. I made the MI diagram do an update during the render() call, instead of a complete re-build of the svg element. I think I got everything.... :)
Also added the click-dblclick chord fix and automatically selecting the status bar text on click so it can be copied, if desired.
=> Mutual info render rework, copy statusbar text

src/Rendering/Chart/Histogram2DPlotlyChartBuilder/index.js
Also provide available chart types, and guard against missing
data.
=> fix(Histogram2DPlotlyChartBuilder): allow setHistogram

src/React/Properties/CheckboxProperty/index.js, src/React/Properties/PropertyFactory/index.js, src/React/Properties/PropertyPanel/example/index.js, src/React/Properties/PropertyPanel/index.js, src/React/Widgets/NumberSliderWidget/index.js, src/React/Widgets/TextInputWidget/index.js, src/React/Widgets/ToggleIconButtonWidget/example/index.js, src/React/Widgets/ToggleIconButtonWidget/index.js, style/ReactProperties/CellProperty.mcss, style/ReactProperties/CheckboxProperty.mcss, style/ReactProperties/PropertyPanel.mcss, style/ReactWidgets/CollapsibleWidget.mcss
Several minor widget changes. 
Added an example for PropertyPanel, as I'm using it elsewhere. 
@jourdain CollapsibleWidget was setting a font-family, which caused consistency problems in my widget. Removing it might affect the appearance of other places that use it. Anything we need to check?
=> Panel widget tweaks

src/React/Widgets/TextInputWidget/index.js
Allows value change to be triggered externally,
and click on icon to send change event.
=> fix(TextInputWidget) icon click handler

src/InfoViz/Native/HistogramSelector/index.js, src/InfoViz/Native/MutualInformationDiagram/example/state.json, src/InfoViz/Native/MutualInformationDiagram/index.js, src/React/Widgets/TextInputWidget/index.js, style/InfoVizNative/HistogramSelector.mcss, style/InfoVizNative/InformationDiagram.mcss
Feedback from our users, and support of using TextInputWidget for search.
For the MutualInformationDiagram, it was unclear which field a click would affect. A low-opacity hover region helps.
@vibraphone This is what I think we decided was the plan...
=> Widget visual, interaction tweaks

src/InfoViz/Native/HistogramSelector/score.js, src/InfoViz/Native/ParallelCoordinates/index.js, style/InfoVizNative/HistogramSelector.mcss
fix(ParallelCoordinates): add tooltip for field name
fix(HistogramSelector): disallow clicking on hidden 'save' icon
=> ParallelCoordinates and HistogramSelector fixes

src/InfoViz/Native/MutualInformationDiagram/index.js, src/React/Widgets/AnnotationStoreEditorWidget/index.js, src/React/Widgets/TextInputWidget/index.js, style/ReactWidgets/AnnotationStoreEditorWidget.mcss
Useful for editing a values one-at-a-time in a series.
AnnotationEditor: Added icons to action buttons
=> fix(TextInputWidget): Allow input to grab focus when rendered.

package.json, src/IO/Core/VTKImageDataModel/index.js, src/Rendering/Geometry/VTKVolumeBuilder/index.js
=> fix(VTKImageDataModel): Add data manager for image data

CONTRIBUTING.md, DEVELOPMENT.md, documentation/content/docs/contributing.md, documentation/content/docs/tools.md, src/NativeUI/Canvas/RemoteRenderer/example/index.md
Add more hyperlinks. Copy root .md into documentation directory as well.
Add a cone to example pvpython server for RemoteRenderer.
=> docs(Contributing, RemoteRenderer): Clarify contribution and dev docs.

package.json, src/IO/WebSocket/ParaViewWebClient/VtkGeometryDelivery.js, src/React/Renderers/VtkGeometryRenderer/index.js, src/React/Renderers/VtkRenderer/index.js
Add new renderer which can subscribe to a view/renderwindow on the server side, and then request
data arrays from the server and render them using vtk.js
=> fix(VtkGeometryRenderer): Add missing renderer

package-lock.json, src/Component/Native/ToggleControl/example/index.js, src/Component/Native/ToggleControl/index.js, src/InfoViz/Core/LegendProvider/example/index.js, style/ComponentNative/ToggleControl.mcss
Bump z-index so it draws on top of parallel coords.
Remove full-height calc, and add a min-height style, so
content resizes naturally.
@jourdain is this what you were thinking? Works for the examples and for divvy.
=> fix(ToggleControl): shrink height, draw on top.

src/Common/Core/CompositeClosureHelper/index.js, src/InfoViz/Native/ParallelCoordinates/index.js
Also fix initial score visibility in ParallelCoordinates
=> fix(CompositeClosureHelper): Add 'has' method for data subscription

src/React/Widgets/ScatterPlotControl/EditView.js, svg/PwfPresets/ExtremesBest.svg, svg/PwfPresets/HighestBest.svg, svg/PwfPresets/LowestBest.svg, svg/PwfPresets/MiddleBest.svg, svg/PwfPresets/index.js
SVG icons and controls for choosing which part of the data to
emphasize.
=> fix(ScatterPlotControl): add in function presets for size/opacity

tools/Vagrantfile
=> chore(Fix Vagrant file for 1 cpu machine):

src/IO/Core/QueryDataModel/index.js, src/Interaction/Core/MouseHandler/index.js
May provide a solution to #412.
=> fix(MouseHandler): Add option to preventDefault on events

src/React/Widgets/EditableListWidget/example/index.js, src/React/Widgets/EditableListWidget/index.js, style/ReactWidgets/EditableListWidget.mcss
Adds initial EditableListWidget. Supports adding, deleting, and resorting.
=> feat(EditableList): Add editable list widget
