.npmignore

As the package.json expose the documentation cli, the install process of ParaViewWeb will fail as the full documentation was ignored. Bringing back the tool and ignoring only the ./documentation/www directory.

fix(npmignore): Fix npmignore to keep the documentation cli

---

documentation/www/source/docs/guides/os_mesa.md

Remove option --enable-texture-float due to patent and license issue

doc(OSMesa): Update build information

---

tools/ansible/roles/apache/vars/RedHat.yml
tools/ansible/roles/paraview/vars/RedHat.yml

Unfortunately include_vars can't be nested in a variable file. So replace with a copy of the vars.

fix(Ansible): Replace include_vars with copy of vars

---

src/React/Widgets/GitTreeWidget/index.js

A single node with without a 'to' property was being treated as a
branch, which was then causing a NAN error when rendering a SVG
path.

fix(Widgets): Guard against undefined 'to' property

---

src/IO/WebSocket/AutobahnConnection/index.js
src/IO/WebSocket/SmartConnect/index.js

Allow the Autobahn retry behaviour to be controlled by passing in a 'retry' property. The default behaviour is not to retry.

fix(IO): Allow retry behaviour to be configured

---

config/webpack.loaders.js

Fix broken loader rule which caused everything matching either
node_modules or paraviewweb to be run through babel, instead of
only things matching node_modules/paraviewweb/.

fix(loaders): Fix loader rule used by other projects

---

src/InfoViz/Native/HistogramSelector/index.js
style/InfoVizNative/HistogramSelector.mcss

When editing scores and the user clicks in a region,
a popup menu appears: choices for changing scores,
creating a new divider. Offset so current score is
under the mouse, and current score color is brighter.
Disappears on mouse-leave.
Cursor changes suggested by Seb - pointer and s-resize
used to indicate edit/view mode changes for scores.
CSS: user-select needs prefixes.

feat(HistogramSelector): popup menu for changing scores

---

src/InfoViz/Core/PartitionProvider/index.js
src/InfoViz/Native/HistogramSelector/Score.js
src/InfoViz/Native/HistogramSelector/example/index.js
src/InfoViz/Native/HistogramSelector/index.js

@jourdain @scottwittenburg Here's the working communication flow. I still needed a .scoreDirty flag so I could make temporary changes to dividers in the client (like dragging or typing in the popups) before I sent them to the server. This then meant I needed the PartitionProvider: partitionChange event to be synchronous, so it always happens before publicAPI.render() and getScores() is called. 
I am planning to squash and re-write commit messages, if it's OK overall.

Histogram Selector scoring communicates partitions with a PartitionProvider

---

src/InfoViz/Native/FieldSelector/index.js
src/InfoViz/Native/HistogramSelector/Score.js
src/InfoViz/Native/HistogramSelector/example/index.js
src/InfoViz/Native/HistogramSelector/index.js
src/InfoViz/Native/ParallelCoordinates/example/index.js
src/InfoViz/Native/ParallelCoordinates/example/state.json
style/InfoVizNative/FieldSelector.mcss
style/InfoVizNative/HistogramSelector.mcss

@scottwittenburg Hover! And more hover!
Add handling for highlighting histogram bins that are hovered
with the mouse, and accept hover events from other components.
Don't generate hover events when editing the partition score,
however - it's too distracting. Clear the hover when editing starts.
Add the HistogramBinHoverProvider to the ParallelCoords example,
and update FieldSelector histogram bin styles to match the
HistogramSelector.

fix(HistogramSelector): Use the HistogramBinHoverProvider

---

src/InfoViz/Core/ScoresProvider/index.js
src/InfoViz/Native/HistogramSelector/score.js

The default score should have an 'isDefault' member, to
match ers server behavior. Don't store the default
separately.
Also make HistogramSelector trigger an annotation edit
when a partition selection is opened for editing, to
make it the 'active' annotation.
@scottwittenburg @jourdain this ok with what you are doing?

fix(ScoresProvider): get default score from score list

---

src/InfoViz/Native/HistogramSelector/example/index.js
src/InfoViz/Native/HistogramSelector/index.js
src/InfoViz/Native/HistogramSelector/score.js
style/InfoVizNative/HistogramSelector.mcss

@scottwittenburg 
New public API for setting boxes/row or single histogram mode, and setting a partition annotation useful for thresholding. HS example has the calls, commented out. 
Setting the threshold annotation also puts it in the mode where the annotation is 'locked' so only the partition value can be changed - no changing scores or deleting/adding partitions.

Histogram legend interaction, single view API

---

src/InfoViz/Native/HistogramSelector/index.js
src/InfoViz/Native/HistogramSelector/score.js

Only allow one histogram to be edited at a time.
Don't show down-arrow cursor or click in bottom bar
to edit scores.
Tweak scroll bar width for windows chrome.

fix(HistogramSelector): only one score edit

---

src/InfoViz/Core/LegendProvider/example/index.js
src/InfoViz/Native/HistogramSelector/example/index.js
src/InfoViz/Native/MutualInformationDiagram/example/index.js
src/InfoViz/Native/ParallelCoordinates/example/index.js
src/React/CollapsibleControls/QueryDataModelControl/example/index.js
src/React/Widgets/AnnotationEditorWidget/example/index.js
src/React/Widgets/ColorMapEditorWidget/example/index.js
src/React/Widgets/DoubleSliderWidget/example/index.js
src/React/Widgets/GitTreeWidget/example/index.js
src/React/Widgets/PieceWiseFunctionEditorWidget/example/index.js
src/React/Widgets/ProxyEditorWidget/example/index.js
src/React/Widgets/SelectionEditorWidget/example/index.js
src/React/Widgets/SvgIconWidget/example/index.js

Internet explorer doesn't support Object.assign() -
import babel-polyfill for examples that need it.
@jourdain it works! There are still some other problems on IE11 though.

fix(examples) Examples need babel-polyfill for IE 11

---

src/InfoViz/Native/HistogramSelector/index.js
src/InfoViz/Native/HistogramSelector/score.js
src/React/Widgets/SelectionEditorWidget/partition/DividerRender.js
style/InfoVizNative/HistogramSelector.mcss

Change to uncertainty in the same units as the histogram.
Max uncertainty is half the histogram range.
Consolidate scoreHelper icon methods. Remove the save icon
completely if there's no annotation store.
Remove unused hobj argument a few places.

fix(HistogramSelector): Abs uncertainty, scoreHelper refactor

---

src/InfoViz/Native/HistogramSelector/score.js

Score region rects could get a negative width when
the score histogram changed to zero width. Make
getRegionBound return [0,1] in that case, to avoid
the error.
@jourdain @scottwittenburg

fix(HistogramSelector): fix negative width error.

---

src/InfoViz/Native/HistogramSelector/score.js
style/InfoVizNative/HistogramSelector.mcss

Emphasize selected histograms with title bar color.
Guard against null drag divider in blur and key handlers.

fix(HistogramSelector): emphasize selected boxes, guard null

---

src/InfoViz/Native/HistogramSelector/index.js
style/InfoVizNative/HistogramSelector.mcss

Hiding the iconCell with a solid background color for the row
causes a white iconCell in Chrome. Hide a nested span instead.
@scottwittenburg

fix(HistogramSelector): no white boxes in Chrome

---

src/InfoViz/Native/HistogramSelector/score.js

Don't stash a reference to the annotation's scores array -
make a copy instead. Fixes updates from the Annot Editor.
@scottwittenburg

fix(HistogramSelector): Fix region update - no references

---

src/IO/Core/ProcessLauncher/index.js
src/InfoViz/Native/HistogramSelector/score.js
src/InfoViz/Native/ParallelCoordinates/index.js
style/ComponentNative/Composite.mcss
style/ComponentReact/WorkbenchController.mcss
style/ReactWidgets/AnnotationEditorWidget.mcss
style/ReactWidgets/AnnotationStoreEditorWidget.mcss
style/ReactWidgets/TextInputWidget.mcss

IE 11 changes:
xhr.requestType = 'json' not supported, detect and parse text.
style display = initial not supported, clear display style instead.
style: flex: 1 on IE 11 defaults to flex: 1 1 auto.
Everyone else uses flex: 1 0 auto. Specify explicitly
so IE 11 will match.
@jourdain I did a search and replace, and mostly verified that things work better on IE 11. Is this enough testing for you?

fix(IE 11): internet explorer 11 compatibility

---

src/InfoViz/Core/Histogram2DProvider/index.js
src/InfoViz/Native/ParallelCoordinates/example/index.js
src/InfoViz/Native/ParallelCoordinates/example/state.json
src/InfoViz/Native/ParallelCoordinates/index.js

Data needed to be updated with 'name' field for extent entries.
Added a guard to Histogram2DProvider to skip check if extent
names are undefined.
Added a render() call so PC will show placeholder when 1 field is
selected.
@jourdain here's the fix...

fix(ParallelCoordinates): Let example render again

---

.eslintrc.js
src/React/Widgets/AnnotationEditorWidget/example/index.js
src/React/Widgets/SelectionEditorWidget/example/index.js
src/React/Widgets/SelectionEditorWidget/partition/index.js

Following a similar method to the HistogramSelector, clamp
values when a range is provided, and clamp uncertainties
so they don't overlap other dividers. Re-sort dividers
when values change order.
Fix example data so uncertainty doesn't overlap.
Fix some linting warnings.

fix(SelectionEditorWidget): clamp uncertainties to prevent overlap

---

src/InfoViz/Native/HistogramSelector/index.js
style/InfoVizNative/HistogramSelector.mcss

Bump from 8pt to 10pt. Icons get bigger, too, adjust size
calc around them. Also fix IE11 bug where +/- boxes/row
disappeared.

fix(HistogramSelector): Make the fieldname font larger

---

style/InfoVizNative/HistogramSelector.mcss

Legend icon was shrinking in external container. Switch from
'padding' to 'margin' to ensure legend SVG has consistent size.

fix(HistogramSelector): Size legend consistently

---

src/InfoViz/Native/ParallelCoordinates/Axis.js
src/InfoViz/Native/ParallelCoordinates/index.js

You can resize a selection bar if you drag within 6 pixels of the
ends, or 1/3 of the bar height, if it's too small. This simple
resize works pretty well, but we may want to allow resize when
starting just outside the bar boundaries, in the future.
If you drag a bar totally off the end of the axis, it is deleted.
@scottwittenburg @jourdain I think this is useful, and we can refine it later, if needed. What do you think?

fix(ParallelCoordinates): Add selection resize, single delete

---

src/React/Renderers/PlotlyRenderer/index.js
src/Rendering/Chart/Histogram2DPlotlyChartBuilder/HistXYZ.js
src/Rendering/Chart/Histogram2DPlotlyChartBuilder/Scatter.js
src/Rendering/Chart/Histogram2DPlotlyChartBuilder/ScatterXY.js
src/Rendering/Chart/Histogram2DPlotlyChartBuilder/index.js

fix(Histogram2DPlotlyChartBuilder): new types, new data type, workbench integration
Add graph types, and allow plotting of x-y scatter data as well.
Allow setting of colormaps. Remove field selector if embedded in workbench.
Add support for chart generated by the server - pass-through builder.

Plotly chart expansion

---

src/Component/Native/Workbench/example/index.js
src/Component/Native/Workbench/index.js

Notify when a renderer becomes visible or hidden due to user actions,
before setContainer() is called on the renderer. Allows just-in-time
data updates, for example.
Updated workbench example to log this event.
@jourdain does passing the renderer match your understanding of what we discussed? It works for what I need...

fix(Workbench): add onVisibilityChange event before viewport viz changes

---

src/React/Widgets/AnnotationEditorWidget/index.js

Make sure the 'weight' parameter is coverted to a number,
by checking for input type==='number'.
@vibraphone

fix(AnnotationEditorWidget): convert 'weight' to number

---

src/React/Widgets/TextInputWidget/index.js

New props allow externally setting the 'editing' state of the
widget, and emitting a change event when pressing 'esc'

fix(TextInputWidget): add props for editing and esc handling

---

src/InfoViz/Native/HistogramSelector/example/index.js

Seems to be an experiment that crept in.

fix(HistogramSelector): example, revert mismatched provider.

---

src/InfoViz/Native/MutualInformationDiagram/example/index.js
src/InfoViz/Native/MutualInformationDiagram/index.js

Track the chord display mode between renders so the current display
is maintained during a resize. Reset when fields are added or removed.
Use the field name as a key for the group, so d3 knows to re-use the
group instead of filling enter() and exit() selections every time
render is called.
Example display tweak (Chrome, windows)

fix(MutualInformationDiagram): Keep chords on resize, reuse groups on render

---

src/InfoViz/Native/HistogramSelector/index.js
src/InfoViz/Native/HistogramSelector/score.js

Don't communicate a threshold annotation with the provider,
and allow a single-sticky name that doesn't exist yet, because
it will soon.

fix(HistogramSelector): threshold annot shouldn't be saved

---

src/InfoViz/Native/HistogramSelector/score.js

A threshold partition needs to be sent to the provider, but only
the source histogram selector should pay attention to it. The annot
editor can still display it read-only, as can ParallelCoords.
In setDefaultScorePartition(), reset the annotation whenever it
doesn't match a single-divider no-yes pattern.

fix(HistogramSelector): fix communication of threshold partitions

---

src/Common/Misc/AnnotationBuilder/index.js
src/InfoViz/Native/HistogramSelector/score.js
src/InfoViz/Native/MutualInformationDiagram/index.js
src/InfoViz/Native/ParallelCoordinates/index.js

Derive from the fields that are in the range annotation when
it is created - it doesn't update as fields are added/removed
from the range annotation. Update might be desirable in the
future.

Fix(AnnotationBuilder): Supply a default name for range annotations

---

src/InfoViz/Native/HistogramSelector/index.js

Remove entry in model.fieldData when a field is deleted. Then
if it comes back, subscription is re-added.

fix(HistogramSelector): track removed fields, so subscriptions update

---

src/InfoViz/Native/HistogramSelector/index.js
style/InfoVizNative/HistogramSelector.mcss

On current Chrome, windows and mac, scrolling in the histogram
selector jumps backwards as we try to re-arrange divs with
transforms. Add an empty span, with full height of the scrolling
container, to force Chrome to correctly calculate the height of
the scrolled div.
@scottwittenburg lovely, eh?

fix(HistogramSelector): Scrolling fix for Chrome

---

config/webpack.loaders.js
src/React/Widgets/InlineSvgIconWidget/index.js

Having an option for doing svg icon widget inline, rather than "<use>"-ing the svg from a sprite, gives application code more ability to select and style the inner parts of the icon via CSS.

fix(InlineSvgIconWidget): Provide inline svg icon widget

---

src/NativeUI/Canvas/RemoteRenderer/example/index.md

Fixed type and authorization key for the ParaView server example.

docs(RemoteRenderer/index.md): Fixed typo and authorization key.

---

config/webpack.loaders.js

Loaders now work with webpack2, even though syntax is still v1
in some places.
@jourdain this is the minimal change needed - we could split and update the chaining syntax, but it's not strictly needed.

fix(webpack): add -loader to work with webpack2

---

config/webpack.loaders.js

Use backward-compatible flag. Works with 0.x versions too.

fix(webpack): loader tweak for svg-sprite-loader v2.0+

---

src/React/Widgets/CountToolbar/index.js
src/React/Widgets/ScatterPlotCameraControl/index.js
src/React/Widgets/ScatterPlotControl/EditView.js
style/ReactWidgets/CountToolbar.mcss
style/ReactWidgets/ScatterPlotControl.mcss

Show the counts of scores in a selection, and toggle them,
via the selection provider.
Let Scatterplot handle activeScores correctly, too.

fix(CountToolbar): Add count toolbar, for selection provider

---

tools/docker/demo/Dockerfile

The default FROM argument is missing a v for the version, I don't think the one without the "v" exists!

Default argument is missing a "v"

---

tools/docker/paraviewweb/scripts/server.sh

In newer pv base images (v5.7.0-RC2 and later), ParaView could be built against either Python 2 or 3.  This change supports finding pip in either case.

chore(docker): Fix how pip is found

---

src/NativeUI/Renderers/NativeImageRenderer/index.js
src/React/Renderers/VtkRenderer/index.js

It cannot recover from websocket shutdown and reconnection, since it sets up
the connection state in componentDidMount and cannot not react to prop changes.
It uses componentWillReceiveProps, which has been deprecated. Another problem
is that the componentWillReceiveProps runs on every render (as far as I can
tell). So VtkRender ends up pushing a SetMaxFrameRate message to the server on
render every time.
This change makes a minimal change to fix both issues, by pushing the state
initialization code to componentDidUpdate, and also cleaning the state up more
properly when the connection object changes.

fix(VtkRenderer): Connection and deprecated API

---

src/Common/Misc/SizeHelper/api.md
src/Common/Misc/SizeHelper/index.js
src/NativeUI/Renderers/NativeImageRenderer/index.js
src/React/Renderers/GeometryRenderer/index.js
src/React/Renderers/ImageRenderer/index.js
src/React/Renderers/MultiLayoutRenderer/index.js
src/React/Renderers/PlotlyRenderer/index.js
src/React/Renderers/VtkRenderer/index.js
src/React/Viewers/LineChartViewer/index.js
src/React/Widgets/EqualizerWidget/index.js
src/React/Widgets/PieceWiseFunctionEditorWidget/index.js
src/React/Widgets/PieceWiseGaussianFunctionEditorWidget/index.js

The current SizeHelper reacts only to explicit window size changes and not to
layout changes inside the window. This change adds a new function
onSizeChangeForElement that uses ResizeObserver to detect when the size of a DOM
element a changes.
ResizeObserver is supported by all modern browsers
now (https://caniuse.com/#feat=resizeobserver).
An aside: I'm not sure if element size caching in SizeHelper is adding much
value. If we remove it, the code will become simpler.

fix(SizeHelper) allow listening to element size changes

---

src/React/Renderers/VtkRenderer/index.js

The BinaryImageStream code path isn't updated, given that it's deprecated.

fix(VtkRenderer): Update the view after window resize
